from pathlib import Path
from typing import Optional

import json
from fastapi import FastAPI, HTTPException, Query


SNAPSHOT_PATH = Path("outputs/foundry_machine_risk_snapshot.json")

app = FastAPI(
    title="Machine Risk API",
    description="Toy API exposing predictive maintenance model outputs for a future Azure AI Foundry agent.",
    version="0.1.0",
)


def load_snapshot() -> list[dict]:
    """
    Load the machine risk snapshot generated by scripts/export_foundry_snapshot.py.
    """
    if not SNAPSHOT_PATH.exists():
        raise FileNotFoundError(
            f"Snapshot file not found at {SNAPSHOT_PATH}. "
            "Run: python scripts/export_foundry_snapshot.py"
        )

    with open(SNAPSHOT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@app.get("/")
def root():
    return {
        "name": "Machine Risk API",
        "description": "Exposes machine-risk predictions for the predictive maintenance copilot.",
        "snapshot_path": str(SNAPSHOT_PATH),
        "available_endpoints": [
            "/machines",
            "/machines/high-risk",
            "/machines/{machine_id}",
            "/plants/{plant_id}/risk-summary",
        ],
    }


@app.get("/machines")
def get_machines(
    risk_band: Optional[str] = Query(
        default=None,
        description="Optional risk band filter: Low, Medium, High, or Critical.",
    ),
    plant_id: Optional[str] = Query(
        default=None,
        description="Optional plant filter, such as Plant-A.",
    ),
):
    machines = load_snapshot()

    if risk_band:
        machines = [
            machine
            for machine in machines
            if machine["risk_band"].lower() == risk_band.lower()
        ]

    if plant_id:
        machines = [
            machine
            for machine in machines
            if machine["plant_id"].lower() == plant_id.lower()
        ]

    return {
        "count": len(machines),
        "machines": machines,
    }


@app.get("/machines/high-risk")
def get_high_risk_machines(
    limit: int = Query(
        default=5,
        ge=1,
        le=25,
        description="Maximum number of high-risk machines to return.",
    )
):
    machines = load_snapshot()

    risky_machines = [
        machine
        for machine in machines
        if machine["risk_band"] in ["High", "Critical"]
    ]

    ranked = sorted(
        risky_machines,
        key=lambda machine: machine["failure_probability"],
        reverse=True,
    )

    return {
        "count": len(ranked[:limit]),
        "machines": ranked[:limit],
    }


@app.get("/machines/{machine_id}")
def get_machine(machine_id: str):
    machines = load_snapshot()

    for machine in machines:
        if machine["machine_id"].lower() == machine_id.lower():
            return machine

    raise HTTPException(
        status_code=404,
        detail=f"Machine {machine_id} was not found in the current risk snapshot.",
    )


@app.get("/plants/{plant_id}/risk-summary")
def get_plant_risk_summary(plant_id: str):
    machines = load_snapshot()

    plant_machines = [
        machine
        for machine in machines
        if machine["plant_id"].lower() == plant_id.lower()
    ]

    if not plant_machines:
        raise HTTPException(
            status_code=404,
            detail=f"No machines found for plant {plant_id}.",
        )

    risk_counts = {
        "Critical": 0,
        "High": 0,
        "Medium": 0,
        "Low": 0,
    }

    for machine in plant_machines:
        risk_counts[machine["risk_band"]] += 1

    highest_risk_machines = sorted(
        plant_machines,
        key=lambda machine: machine["failure_probability"],
        reverse=True,
    )[:5]

    average_failure_probability = round(
        sum(machine["failure_probability"] for machine in plant_machines)
        / len(plant_machines),
        3,
    )

    return {
        "plant_id": plant_id,
        "machine_count": len(plant_machines),
        "average_failure_probability": average_failure_probability,
        "risk_counts": risk_counts,
        "highest_risk_machines": highest_risk_machines,
    }